In [35]:
import pandas_datareader.data as web
import datetime
import pandas as pd
import numpy as np

In [36]:
start = datetime.datetime(2020,1,1)
end = datetime.datetime(2020,12,31)
stocks = ['KBC.BR', "UCB.BR"]
n = len(stocks)
r = 0.01
def ImportData(name, start, end):
    n = len(name)
    ptf = pd.DataFrame()
    for i in range(n):
        tmp = pd.DataFrame(web.DataReader(name[i],'yahoo', start, end)["Close"])
        ptf = pd.concat([ptf, tmp], axis = 1)
    ptf.columns = name
    returns = np.log(ptf/ptf.shift(1))
    returns = returns.dropna()
    return(returns)

Stocks_return = ImportData(stocks, start, end)

In [37]:
mu = np.transpose(np.array([np.mean(Stocks_return)]))
covariance = np.cov(Stocks_return, rowvar = False)
inv_covariance = np.linalg.inv(covariance)
e = np.full((n,1), 1)
gamma = 10
Lambda = (np.transpose(e) @ inv_covariance @ mu - gamma)/(np.transpose(e) @ inv_covariance @ e)
w = (1/gamma) * inv_covariance @ (mu - Lambda*e)
w_r = (1/gamma) * inv_covariance @ (mu - r*e)

In [38]:
sum(w)

array([1.])

In [39]:
w_r

array([[-0.55190205],
       [-1.36464562]])

In [40]:
1 - sum(w_r) + sum(w_r)

array([1.])

In [44]:
print("Portfolio expected return = ", np.transpose(w) @ mu)

Portfolio expected return =  [[0.00048392]]


In [45]:
print("Portfolio variance = ", np.transpose(w) @ covariance @ w)

Portfolio variance =  [[0.00051776]]


In [47]:
print("Portfolio expected return with free risk asset = ", np.transpose(w_r) @ mu + (1- np.transpose(w_r) @ e) * r)

Portfolio expected return with free risk asset =  [[0.02864498]]


In [48]:
print("Portfolio variance with free risk asset = ", np.transpose(w_r) @ covariance @ w_r)

Portfolio variance with free risk asset =  [[0.0018645]]
